# Generated by Django 4.1.7 on 2023-04-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
