# Generated by Django 4.1.7 on 2023-04-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0002_product_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name'], name='mainstore_c_first_n_8ae395_idx'),
        ),
    ]
