# Generated by Django 4.1.7 on 2023-04-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0003_customer_mainstore_c_first_n_8ae395_idx'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO mainstore_collection (title)
            VALUES ('Grocery')
        """,
        """
            DELETE FROM mainstore_collection
            WHERE title = 'Grocery'
        """)
    ]
