# Generated by Django 4.1.7 on 2023-04-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0004_auto_20230403_2200'),
    ]

    operations = [
         migrations.RunSQL("""
            INSERT INTO mainstore_collection (title)
            VALUES ('Clothes')
        """,
        """
            DELETE FROM mainstore_collection
            WHERE title = 'Clothes'
        """)
    ]
