# Generated by Django 4.1.7 on 2023-04-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0005_auto_20230404_1101'),
    ]

    operations = [
        
        migrations.RunSQL("""
            INSERT INTO mainstore_collection (title)
            VALUES ('Toys'), ('Ladies')
        """,
        """
            DELETE FROM mainstore_collection
            WHERE title = 'Toys' AND title = 'Ladies'
        """)
    ]
